index:
    path: /
    controller: 'App\Controller\DefaultController::indexAction'

stream:
    path: /stream
    controller: 'App\Controller\FileDownloadController::streamOrDownloadAction'

library.stream:
    path: /library/{libraryFileId}/stream
    controller: 'App\Controller\BrowseLibraryController::streamFileByIdAction'

library.delete:
    path: /library/{libraryId}/{url}
    methods: ['DELETE']
    controller: 'App\Controller\BrowseLibraryController::deleteByIdAction'

library.add:
    path: /library/{libraryId}/{url}
    methods: ['POST']
    controller: 'App\Controller\BrowseLibraryController::addFileAction'

library.options:
    path: /library/{libraryId}/{url}
    methods: ['OPTIONS']
    controller: 'App\Controller\BrowseLibraryController::displayOptionsAction'

library.browse:
    path: /library/browse/{perPage}/{page}
    methods: ['GET']
    controller: 'App\Controller\BrowseLibraryController::browseAction'
    defaults:
        perPage: 50
        page: 1
